### ISSUE TITLE
Update all if/else functions using the new logic

### ISSUE THREAD

**Issue by xaviernogueira** [EcohydrologyTeam/ClearWater-modules#39]
So in [`running_process_funcs.ipynb`](https://github.com/EcohydrologyTeam/ClearWater-modules-python/blob/main/examples/dev_sandbox/running_process_funcs.ipynb) and #31 I assessed options to run if/else logic for our process functions.

My findings are recorded in PR #36 

In summary, one should use `xr.where()` WITHOUT `@numba.njit`. For example, the below function will return 1 if a cell value in `combo` is > 1243597, and 0 if not.

```python
def mock_2(air, air2, air3):
    combo = air * 0.01 * air2 * air3
    return xr.where(combo > 1243597, 1, 0)
```

**Tasks:**
- [x] Finish getting TSM 100% working by implementing the above logic for Reynold's number stuff.
- [ ] @imscw95 @kewalak apply this logic wherever is necessary in NSM. Feel free to reach out with questions, the documentation for `xarray.where` is [here](https://docs.xarray.dev/en/stable/generated/xarray.where.html).

**Comment by xaviernogueira** [comment]
Yes. The one slightly odd thing about the code architecture is that since everything is done via xarray and share a computational engine, things like that (boolean variables) will have to be in a grid. So `use_Algae` should be a grid where every value is `True` or `False`. Analogous to a "mask" grid.

And then `xr.where` can be used in the process function to apply the logic.

**Comment by kewalak** [comment]
@xaviernogueira is there is best way to do multiple if/elseif/elseif conditions? Or if statements within if statements?

**Comment by aufdenkampe** [comment]
@kewalak, I just recently notice this need for nested logic, and am discussing options here:
- https://github.com/EcohydrologyTeam/ClearWater-modules/pull/44#pullrequestreview-1672745595

@xaviernogueira's initial implementation was to nest multiple `xr.where()` function, as you can see in the code review comment. However, that's not entirely elegant and may have performance issues.

The [numpy.select()](https://numpy.org/doc/stable/reference/generated/numpy.select.html) function can do multiple conditions very well, but I'm not sure if that will work for Xarray. @xaviernogueira, can you look into this?

**Comment by xaviernogueira** [comment]
@aufdenkampe there is no `numpy.select()` equivalent for xarray, however, if you prefer, I can use the numpy function and write back to the data-array. This will potentially be slower, but I can assess it.

**Comment by aufdenkampe** [comment]
@xaviernogueira, the idea to try implementing `numpy.select()` directly might be worth trying quickly, but if it is slower than a nested `xr.where()` then we would want to skip it. 

Can you set up a quick performance test of the various approaches, not just looking for speed but also memory usage. My worry with nested `xr.where()` (and in general) are approaches that copy the entire dataset multiple times.

In general, we're looking for [zero-copy](https://en.wikipedia.org/wiki/Zero-copy) approaches, given that these algorithms will be implemented over millions of cells.

**Comment by xaviernogueira** [comment]
Closing this issue now that we switched to using `numpy.select()` in PR #44 . If the switch has not been applied in other modules, it should be done going forward.

**Comment by xaviernogueira** [comment]
Closing
