### ISSUE TITLE
GSM - rate coefficients for different orders

### ISSUE THREAD

**Issue by sjordan29** [EcohydrologyTeam/ClearWater-modules#7]
@sjordan29 Just a heads up, we need to change the formulation of this module to match the fortran's correctly. I have attached an screen shot from an email I sent about the inaccuracy in the python. The fortran is correct. I plan to work on this soon, but am busy with some other tasks at the moment. Will it affect your ability to vectorize the code? 

![GSM Differences Python Fortran](https://user-images.githubusercontent.com/66634423/207718470-e701d617-d308-4a11-a761-3a8f22b59721.PNG)

_Originally posted by @imscw95 in https://github.com/EnvironmentalSystems/ClearWater-modules-python/issues/4#issuecomment-1352228261_

**Comment by xaviernogueira** [comment]
@imscw95 is this done or outdated? If so let's close it out.

**Comment by imscw95** [comment]
Outdated.
